SELECT p.PRODUCTO_NO, p.PRECIO_ACTUAL, p.DESCRIPCION, c.NOMBRE, ifnull(SUM(pe.UNIDADES )*p.PRECIO_ACTUAL,0) AS 'Total'
FROM PRODUCTOS p
JOIN PEDIDOS pe ON p.PRODUCTO_NO = pe.PRODUCTO_NO
JOIN CLIENTES c ON pe.CLIENTE_NO = c.CLIENTE_NO
GROUP BY p.PRODUCTO_NO
HAVING Total BETWEEN 2000 AND 4000;